######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 15 15:46:58 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyPaint.h
SOURCES += main.cpp MyPaint.cpp
